import * as cheerio from "cheerio";
import { getSql } from "@/lib/db";

type SchoolType = "k12" | "higher_ed";
type Agency = { id:string; canonical_name:string; website:string; agency_type:string };
type Candidate = { full_name:string; title:string; role_family:string; email:string|null; phone:string|null; source_url:string; confidence:number };

const EMAIL=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig;
const PHONE=/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}/;
const BAD_EMAIL=/^(info|support|webmaster|communications|help|office|contact|admin|hr|registrar|admissions|noreply|no-reply)@/i;
const BLOCKED_SITE=/(nces\.ed\.gov|ionwave|opengov|oregonbuys|bidnet|publicpurchase|bonfirehub|jaggaer|bidsync|periscope|commbuys|bidbuy\.illinois|sigma\.michigan|mevss\.hostams|doa\.louisiana|caleprocure|scbo\.sc\.gov|app\.az\.gov|eva\.virginia\.gov|mvendor\.cgieva\.com|evp\.nc\.gov|vendorregistry|planetbids|myfloridamarketplace)/i;

const ROLE_RULES:Array<{family:string; re:RegExp}> = [
  {family:"Security",re:/\b(chief of police|police chief|director of (?:public safety|campus safety|security|safety|school safety|safety and security)|executive director of (?:public safety|security|safety)|vice president of public safety|assistant vice president of public safety|chief security officer|security director|public safety director|campus safety director|emergency management|emergency preparedness|safe schools|safety coordinator|security coordinator)\b/i},
  {family:"Facilities",re:/\b(vice president of facilities|associate vice president of facilities|assistant vice president of facilities|director of facilities|facilities director|director of capital projects|capital projects director|director of planning design and construction|director of planning, design and construction|facilities manager|buildings? and grounds|director of operations|chief operating officer|chief operations officer|maintenance director)\b/i},
  {family:"Technology",re:/\b(chief information officer|chief technology officer|\bcio\b|\bcto\b|director of information technology|director of technology|technology director|it director|director of infrastructure|network director|information systems director|technology services director)\b/i},
  {family:"Procurement",re:/\b(director of procurement|procurement director|director of purchasing|purchasing director|chief procurement officer|procurement manager|purchasing manager|director of business services|school business administrator|chief financial officer|\bcfo\b)\b/i},
  {family:"Executive",re:/\b(superintendent|deputy superintendent|assistant superintendent|president|chancellor|vice chancellor|chief of staff)\b/i},
  {family:"Risk",re:/\b(director of risk management|risk manager|risk management director|director of emergency management|emergency management director)\b/i},
];

const K12_PATHS=["/staff","/staff-directory","/directory","/administration","/leadership","/departments","/district-office","/safety","/security","/school-safety","/public-safety","/facilities","/operations","/technology","/information-technology","/procurement","/purchasing","/business-services","/superintendent"];
const HIGHER_PATHS=["/directory","/leadership","/administration","/public-safety","/campus-safety","/police","/security","/emergency-management","/facilities","/facilities-management","/planning-design-construction","/capital-projects","/information-technology","/it","/procurement","/purchasing","/risk-management"];

function clean(s:string){return s.replace(/\s+/g," ").trim();}
function safeUrl(raw:string){try{const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!/^https?:$/.test(u.protocol))return null;const h=u.hostname.toLowerCase();if(h==="localhost"||/^127\.|^10\.|^192\.168\.|^169\.254\./.test(h)||BLOCKED_SITE.test(u.toString()))return null;return u;}catch{return null;}}
function sameHost(a:URL,b:URL){return a.hostname.replace(/^www\./,"")===b.hostname.replace(/^www\./,"");}
function titleCase(s:string){return s.toLowerCase().replace(/(^|[\s'.-])([a-z])/g,(_,a,b)=>a+b.toUpperCase());}
function plausibleName(raw:string){let s=clean(raw.replace(EMAIL," ").replace(PHONE," ").replace(/[^A-Za-z.' -]/g," "));if(s.length<5||s.length>60)return null;const p=s.split(/\s+/);if(p.length<2||p.length>5)return null;if(/director|chief|president|superintendent|security|safety|facilities|technology|procurement|purchasing|department|office|staff|contact|university|college|school|district/i.test(s))return null;if(!p.every(x=>/^[A-Za-z][A-Za-z.'-]*$/.test(x)))return null;return titleCase(s);}
function role(text:string){for(const r of ROLE_RULES)if(r.re.test(text))return r;return null;}

async function fetchHtml(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{redirect:"follow",cache:"no-store",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; Pursuit-Raven/3.1; public-directory-research)",accept:"text/html,application/xhtml+xml"}});if(!r.ok)return null;const ct=(r.headers.get("content-type")||"").toLowerCase();if(!ct.includes("html"))return null;return {html:await r.text(),url:r.url||url};}catch{return null;}finally{clearTimeout(t);}}

function discover(base:URL,html:string,kind:SchoolType){const $=cheerio.load(html);const scored=new Map<string,number>();$("a[href]").each((_,e)=>{const href=$(e).attr("href")||"";const label=clean($(e).text());try{const u=new URL(href,base);if(!sameHost(base,u)||!/^https?:$/.test(u.protocol)||BLOCKED_SITE.test(u.toString()))return;const text=`${label} ${u.pathname}`;let score=0;if(/public safety|campus safety|school safety|security|police|emergency/i.test(text))score+=60;if(/facilities|capital|construction|planning/i.test(text))score+=45;if(/information technology|technology|infrastructure|network/i.test(text))score+=40;if(/procurement|purchasing|business services/i.test(text))score+=40;if(/staff|directory|leadership|administration|departments/i.test(text))score+=25;if(/news|calendar|athletics|admissions|student|library|alumni|facebook|instagram|youtube/i.test(text))score-=30;if(score>0)scored.set(u.toString(),Math.max(score,scored.get(u.toString())||0));}catch{}});for(const p of(kind==="k12"?K12_PATHS:HIGHER_PATHS)){const u=new URL(p,base).toString();scored.set(u,Math.max(20,scored.get(u)||0));}return [...scored.entries()].sort((a,b)=>b[1]-a[1]).slice(0,14).map(x=>x[0]);}

function extract(html:string,source:string){const $=cheerio.load(html);const out:Candidate[]=[];const nodes=$("article,li,tr,.staff,.staff-member,.staff-card,.person,.employee,.directory-item,.contact,.profile,.card,section,div").toArray();for(const el of nodes){const n=$(el);const text=clean(n.text());if(text.length<12||text.length>800)continue;const rr=role(text);if(!rr)continue;const email=(n.find('a[href^="mailto:"]').first().attr("href")||"").replace(/^mailto:/i,"").split("?")[0]||text.match(EMAIL)?.[0]||null;const phone=(n.find('a[href^="tel:"]').first().attr("href")||"").replace(/^tel:/i,"")||text.match(PHONE)?.[0]||null;const title=(n.find(".title,.position,.job-title,.role,.staff-title").first().text()||text.match(rr.re)?.[0]||"").trim().slice(0,140);const nameBits=[n.find("h1,h2,h3,h4,strong,b,.name,.staff-name,.person-name,.employee-name").first().text(),n.find("a").filter((_,a)=>!/^mailto:|^tel:/i.test($(a).attr("href")||"")).first().text(),...text.split(/\||•|\n| - /).slice(0,5)];let name:string|null=null;for(const bit of nameBits){name=plausibleName(bit);if(name)break;}if(!name&&email&&!BAD_EMAIL.test(email))name=plausibleName(email.split("@")[0].replace(/[._-]+/g," "));if(!name)continue;out.push({full_name:name,title:title||rr.family,role_family:rr.family,email:email&&!BAD_EMAIL.test(email)?email:null,phone:phone||null,source_url:source,confidence:email&&!BAD_EMAIL.test(email)?96:phone?90:80});}
 const dedupe=new Map<string,Candidate>();for(const c of out){const k=`${c.full_name}|${c.role_family}`.toLowerCase();const old=dedupe.get(k);if(!old||c.confidence>old.confidence||(!old.email&&c.email))dedupe.set(k,c);}return [...dedupe.values()].slice(0,30);
}

async function persist(agency:Agency,candidates:Candidate[]){if(!candidates.length)return 0;const sql=getSql();let n=0;for(const c of candidates){await sql.query(`insert into raven_people(agency_id,full_name,title,role_family,email,phone,source_url,source_type,confidence,last_verified_at,updated_at) values($1::uuid,$2,$3,$4,$5,$6,$7,'public_web_fast',$8,now(),now()) on conflict(agency_id,full_name,title) do update set role_family=excluded.role_family,email=coalesce(excluded.email,raven_people.email),phone=coalesce(excluded.phone,raven_people.phone),source_url=excluded.source_url,confidence=greatest(raven_people.confidence,excluded.confidence),last_verified_at=now(),updated_at=now()`,[agency.id,c.full_name,c.title,c.role_family,c.email,c.phone,c.source_url,c.confidence]);n++;}return n;}

async function enrichOne(agency:Agency,kind:SchoolType){const base=safeUrl(agency.website);if(!base)return {agency:agency.canonical_name,people:0,pages:0,ok:false};const home=await fetchHtml(base.toString());if(!home)return {agency:agency.canonical_name,people:0,pages:0,ok:false};let candidates=extract(home.html,home.url);let pages=1;const urls=discover(new URL(home.url),home.html,kind);for(const url of urls){if(pages>=10)break;const page=await fetchHtml(url);if(!page)continue;pages++;candidates.push(...extract(page.html,page.url));if(new Set(candidates.map(c=>c.role_family)).size>=4&&candidates.filter(c=>c.email).length>=3)break;}const dedupe=[...new Map(candidates.map(c=>[`${c.full_name}|${c.role_family}`.toLowerCase(),c])).values()];const people=await persist(agency,dedupe);const sql=getSql();await sql.query(`insert into raven_enrichment_runs(agency_id,status,started_at,completed_at,pages_fetched,people_found,diagnostics) values($1::uuid,'success',now(),now(),$2,$3,jsonb_build_object('worker','school-contact-fast','kind',$4::text))`,[agency.id,pages,people,kind]);return {agency:agency.canonical_name,people,pages,ok:true};}

export async function enrichSchoolContactsFast(kind:SchoolType,limit=24){const sql=getSql();const agencyTypes=kind==="k12"?["k12"]:["higher_ed"];const rows=await sql.query(`select a.id::text,a.canonical_name,a.website,a.agency_type from agencies a where a.agency_type=any(string_to_array($1::text, ',')) and a.website is not null and a.website<>'' and a.website !~* $3::text and not exists(select 1 from raven_enrichment_runs r where r.agency_id=a.id and r.started_at>now()-interval '14 days' and coalesce(r.diagnostics->>'worker','')='school-contact-fast') order by (select count(*) from raven_people p where p.agency_id=a.id) asc, case when exists(select 1 from opportunities o where o.agency_id=a.id and o.status='open') then 0 else 1 end, a.canonical_name limit $2`,[agencyTypes.join(','),Math.max(1,Math.min(limit,40)),BLOCKED_SITE.source]) as Agency[];const results:any[]=[];for(let i=0;i<rows.length;i+=6){const chunk=rows.slice(i,i+6);results.push(...await Promise.all(chunk.map(a=>enrichOne(a,kind))));}return {kind,selected:rows.length,completed:results.filter(x=>x.ok).length,people:results.reduce((s,x)=>s+Number(x.people||0),0),pages:results.reduce((s,x)=>s+Number(x.pages||0),0),results};}
