import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";
import * as XLSX from "xlsx";

export const dynamic="force-dynamic";
export const maxDuration=300;
const SOURCE="https://doe.sd.gov/ofm/documents/1025-SupsAdmin.xlsx";
type Contact={district:string;fullName:string;email:string|null;phone:string|null};
type Slot={id:string;canonical_name:string|null;county:string|null};
function clean(v:any){return String(v??"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim();}
function norm(v:any){return clean(v).toLowerCase().replace(/\b(public|school|schools|district)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function findKey(keys:string[],rx:RegExp){return keys.find(k=>rx.test(clean(k)))||"";}
function person(v:any){const s=clean(v).replace(/^(Dr\.?|Mr\.?|Mrs\.?|Ms\.?)\s+/i,"");return s.split(/\s+/).length>=2?s:"";}
async function roster(){const r=await fetch(SOURCE,{cache:"no-store",redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; Pursuit-Raven/10.2; authoritative-state-roster)",accept:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,*/*"}});if(!r.ok)throw new Error(`SD DOE workbook HTTP ${r.status}`);const wb=XLSX.read(new Uint8Array(await r.arrayBuffer()),{type:"array"});const out:Contact[]=[];for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json<Record<string,any>>(wb.Sheets[sn],{defval:""});if(!rows.length)continue;const keys=Object.keys(rows[0]);const dk=findKey(keys,/(district|system|organization).*(name)?|^district$/i);const nk=findKey(keys,/(superintendent.*name|superintendent|administrator.*name)/i);const ek=findKey(keys,/e-?mail/i);const pk=findKey(keys,/phone|telephone/i);if(!dk||!nk)continue;for(const row of rows){const district=clean(row[dk]),fullName=person(row[nk]);if(!district||!fullName||/non.?public|tribal|special|cooperative/i.test(district))continue;out.push({district,fullName,email:ek&&/@/.test(clean(row[ek]))?clean(row[ek]):null,phone:pk?clean(row[pk])||null:null});}}
 const d=[...new Map(out.map(x=>[norm(x.district),x])).values()];if(d.length<120)throw new Error(`SD DOE parser guard: only ${d.length} superintendent records parsed`);return d;}
function match(c:Contact,slots:Slot[]){const k=norm(c.district);let a=slots.filter(s=>norm(s.canonical_name)===k);if(a.length===1)return a[0];a=slots.filter(s=>{const x=norm(s.canonical_name);return x&&k&&(x.includes(k)||k.includes(x));});return a.length===1?a[0]:null;}
export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='SD' and scope='district' and role_key='superintendent'`)as any[])[0];let list:Contact[]=[];try{list=await roster();}catch(e){return NextResponse.json({ok:false,state:'SD',source:SOURCE,blocker:e instanceof Error?e.message:String(e),before},{status:502});}const slots=await sql.query(`select c.id::text,c.county,a.canonical_name from raven_state_contacts c left join agencies a on a.id=c.agency_id where c.state_code='SD' and c.scope='district' and c.role_key='superintendent'`)as Slot[];let matched=0,written=0;const unmatched:string[]=[];for(const c of list){const s=match(c,slots);if(!s){unmatched.push(c.district);continue;}matched++;const u=await sql.query(`update raven_state_contacts set full_name=$2,title='Superintendent',email=$3,phone=$4,source_url=$5,verification_status='verified',verified_at=now(),evidence_note='Current superintendent contact published in the South Dakota Department of Education statewide Superintendents, Administrators and District Info workbook.',updated_at=now() where id=$1 and verification_status in ('missing','candidate','rejected') returning id`,[s.id,c.fullName,c.email,c.phone,SOURCE])as any[];written+=u.length;}const after=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='SD' and scope='district' and role_key='superintendent'`)as any[])[0];return NextResponse.json({ok:true,state:'SD',source:SOURCE,parsed:list.length,matched,written,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,20),before,after,verifiedAdded:Number(after.verified)-Number(before.verified)});}
