import * as cheerio from "cheerio";
import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic="force-dynamic";
export const maxDuration=300;
const SOURCE="https://www.va-doeapp.com/SuperintendentBySchoolDivisions.aspx?w=true";

type Contact={division:string;fullName:string;phone:string|null};
type Slot={id:string;canonical_name:string|null;county:string|null};
function clean(v:any){return String(v??"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim();}
function norm(v:any){return clean(v).toLowerCase().replace(/&/g," and ").replace(/\b(public|school|schools|division|city|county)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function person(v:string){return clean(v).replace(/^(Dr\.?|Mr\.?|Mrs\.?|Ms\.?|Miss)\s+/i,"").replace(/,?\s*(Ed\.?D\.?|Ph\.?D\.?)$/i,"").trim();}
async function roster(){const r=await fetch(SOURCE,{cache:"no-store",redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; Pursuit-Raven/10.1; authoritative-state-roster)",accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`VDOE directory HTTP ${r.status}`);const $=cheerio.load(await r.text());const out:Contact[]=[];$("tr").each((_,tr)=>{const c=$(tr).find("th,td").map((__,td)=>clean($(td).text())).get();if(c.length<3)return;const division=c[0],raw=c[1];if(!division||!raw||/school division|superintendent/i.test(division)||/position vacant/i.test(raw))return;const name=person(raw);if(name.split(/\s+/).length<2)return;const ph=c.find(x=>/\d{3}[- .]\d{3}[- .]\d{4}/.test(x));out.push({division,fullName:name,phone:ph?(ph.match(/\d{3}[- .]\d{3}[- .]\d{4}/)||[])[0]:null});});const d=[...new Map(out.map(x=>[norm(x.division),x])).values()];if(d.length<115)throw new Error(`VDOE parser guard: only ${d.length} superintendent records parsed`);return d;}
function match(c:Contact,slots:Slot[]){const k=norm(c.division);let a=slots.filter(s=>norm(s.canonical_name)===k);if(a.length===1)return a[0];a=slots.filter(s=>norm(s.county)===k);if(a.length===1)return a[0];a=slots.filter(s=>{const x=norm(s.canonical_name);return x&&k&&(x.includes(k)||k.includes(x));});return a.length===1?a[0]:null;}
export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='VA' and scope='district' and role_key='superintendent'`)as any[])[0];let list:Contact[]=[];try{list=await roster();}catch(e){return NextResponse.json({ok:false,state:'VA',source:SOURCE,blocker:e instanceof Error?e.message:String(e),before},{status:502});}const slots=await sql.query(`select c.id::text,c.county,a.canonical_name from raven_state_contacts c left join agencies a on a.id=c.agency_id where c.state_code='VA' and c.scope='district' and c.role_key='superintendent'`)as Slot[];let matched=0,written=0;const unmatched:string[]=[];for(const c of list){const s=match(c,slots);if(!s){unmatched.push(c.division);continue;}matched++;const u=await sql.query(`update raven_state_contacts set full_name=$2,title='Superintendent',email=null,phone=$3,source_url=$4,verification_status='verified',verified_at=now(),evidence_note='Current public school division superintendent and phone published in the Virginia Department of Education statewide Division Superintendent Listing.',updated_at=now() where id=$1 and verification_status in ('missing','candidate','rejected') returning id`,[s.id,c.fullName,c.phone,SOURCE])as any[];written+=u.length;}const after=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='VA' and scope='district' and role_key='superintendent'`)as any[])[0];return NextResponse.json({ok:true,state:'VA',source:SOURCE,parsed:list.length,matched,written,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,20),before,after,verifiedAdded:Number(after.verified)-Number(before.verified)});}
