import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";
import { extractText, getDocumentProxy } from "unpdf";

export const dynamic="force-dynamic";
export const maxDuration=300;
const SOURCE="https://www.oregon.gov/ode/about-us/Documents/CombinedDirectory_20260715_025605.pdf";

type Contact={district:string;fullName:string;email:string|null;phone:string|null;institutionId:string|null};
type Slot={id:string;canonical_name:string|null;county:string|null};
function clean(v:any){return String(v??"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim();}
function norm(v:any){return clean(v).toLowerCase().replace(/&/g," and ").replace(/\b(public|school|schools|district|administrative|unified|community)\b/g," ").replace(/\bsd\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function person(v:string){return clean(v).replace(/^(Dr\.?|Mr\.?|Mrs\.?|Ms\.?)\s+/i,"").replace(/\s+(?:\d{3}[- .]\d{3}[- .]\d{4}.*)$/," ").trim();}
function plausibleDistrict(v:string){const s=clean(v);return s.length>2&&s.length<100&&!/education service|\besd\b|regional service|private|academy|charter school|elementary|elem\b|middle|high\b|community college|university/i.test(s);}
function looksDistrict(v:string){const s=clean(v);return /\bSD\s*\d|school district|public schools|public school district/i.test(s);}
function getEmail(lines:string[]){for(const x of lines){const m=x.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);if(m)return m[0];}return null;}
function getPhone(lines:string[]){for(const x of lines){const m=x.match(/(?:\(?\d{3}\)?[- .])\d{3}[- .]\d{4}/);if(m)return m[0];}return null;}
async function roster(){const r=await fetch(SOURCE,{cache:"no-store",redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; Pursuit-Raven/11.0; authoritative-state-roster)",accept:"application/pdf,*/*"}});if(!r.ok)throw new Error(`ODE directory HTTP ${r.status}`);const pdf=await getDocumentProxy(new Uint8Array(await r.arrayBuffer()));const out:any=await extractText(pdf,{mergePages:true});const text=typeof out?.text==="string"?out.text:Array.isArray(out?.text)?out.text.join("\n"):String(out||"");const lines=text.split(/\r?\n/).map(clean).filter(Boolean);const contacts:Contact[]=[];for(let i=0;i<lines.length-2;i++){const district=lines[i];if(!looksDistrict(district)||!plausibleDistrict(district))continue;if(!/^Institution ID:/i.test(lines[i+1]))continue;const inst=(lines[i+1].match(/Institution ID:\s*(\d+)/i)||[])[1]||null;let end=Math.min(lines.length,i+30);for(let j=i+2;j<end;j++){if(/^Institution ID:/i.test(lines[j])){end=j;break;}}const block=lines.slice(i+2,end);let fullName="";for(const x of block){const m=x.match(/^Superintendent\s+(.+)$/i);if(m){fullName=person(m[1]);break;}}if(!fullName||fullName.split(/\s+/).length<2)continue;contacts.push({district,fullName,email:getEmail(block),phone:getPhone(block),institutionId:inst});}const dedup=[...new Map(contacts.map(c=>[norm(c.district),c])).values()];if(dedup.length<175)throw new Error(`ODE parser confidence guard: only ${dedup.length} regular-district superintendent records parsed; no writes performed`);return dedup;}
function match(c:Contact,slots:Slot[]){const k=norm(c.district);let a=slots.filter(s=>norm(s.canonical_name)===k);if(a.length===1)return a[0];a=slots.filter(s=>{const x=norm(s.canonical_name);return x&&k&&(x.includes(k)||k.includes(x));});return a.length===1?a[0]:null;}
export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='OR' and scope='district' and role_key='superintendent'`)as any[])[0];let list:Contact[]=[];try{list=await roster();}catch(e){return NextResponse.json({ok:false,state:'OR',source:SOURCE,blocker:e instanceof Error?e.message:String(e),before},{status:502});}const slots=await sql.query(`select c.id::text,c.county,a.canonical_name from raven_state_contacts c left join agencies a on a.id=c.agency_id where c.state_code='OR' and c.scope='district' and c.role_key='superintendent'`)as Slot[];let matched=0,written=0;const unmatched:string[]=[];for(const c of list){const s=match(c,slots);if(!s){unmatched.push(c.district);continue;}matched++;const u=await sql.query(`update raven_state_contacts set full_name=$2,title='Superintendent',email=$3,phone=$4,source_url=$5,verification_status='verified',verified_at=now(),evidence_note='Current superintendent contact published in the official 2026-27 Oregon Department of Education School Directory.',updated_at=now() where id=$1 and verification_status in ('missing','candidate','rejected') returning id`,[s.id,c.fullName,c.email,c.phone,SOURCE])as any[];written+=u.length;}const after=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='OR' and scope='district' and role_key='superintendent'`)as any[])[0];return NextResponse.json({ok:true,state:'OR',source:SOURCE,parsed:list.length,matched,written,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,25),before,after,verifiedAdded:Number(after.verified)-Number(before.verified)});}
