import { NextRequest, NextResponse } from "next/server";
import * as cheerio from "cheerio";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const STATES = ['AL','AZ','AR','CA','CO','CT','DE','FL','GA','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'];
const LIMIT = 100;
const CONCURRENCY = 12;
const TIMEOUT = 6500;
const BUDGET = 260000;
const PATHS = ['/superintendent','/superintendents-office','/superintendent-office','/administration','/district-office','/leadership','/staff','/staff-directory','/directory','/about/leadership'];
const TITLE_RX = /\b(superintendent of schools|district superintendent|school superintendent|superintendent)\b/i;
const EXCLUDE_TITLE_RX = /\b(assistant|associate|deputy|interim assistant|executive assistant|secretary to|administrative assistant|assistant to)\s+(?:the\s+)?superintendent\b/i;
const EMAIL_RE = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;
const PHONE_RE = /(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}(?:\s*(?:x|ext\.?|extension)\s*\d+)?/i;
const BAD_NAME = /^(superintendent|office of the superintendent|superintendent's office|district office|administration|leadership|staff directory|contact us|email|phone|home)$/i;

type Agency={id:string;canonical_name:string;website:string};
type Hit={full_name:string;title:string;email:string|null;phone:string|null;source_url:string;score:number};
function clean(v:string){return String(v||'').replace(/\s+/g,' ').trim();}
function plausibleName(v:string){const s=clean(v.replace(/^(dr\.?|mr\.?|mrs\.?|ms\.?)\s+/i,'').replace(/[^A-Za-z.' -]/g,' '));if(!s||BAD_NAME.test(s)||s.length<5||s.length>70)return null;const p=s.split(/\s+/).filter(Boolean);if(p.length<2||p.length>5)return null;if(/superintendent|school|district|office|administration|leadership|director|assistant|department|contact|email|phone/i.test(s))return null;return p.every(x=>/^[A-Za-z][A-Za-z.'-]*$/.test(x))?s:null;}
function safe(raw:string){try{const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);return /^https?:$/.test(u.protocol)?u:null;}catch{return null;}}
function host(u:URL){return u.hostname.toLowerCase().replace(/^www\./,'');}
function sameHost(a:URL,b:URL){const x=host(a),y=host(b);return x===y||x.endsWith(`.${y}`)||y.endsWith(`.${x}`);}
async function fetchHtml(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{cache:'no-store',redirect:'follow',signal:c.signal,headers:{'user-agent':'Mozilla/5.0 (compatible; Pursuit Raven Superintendent Completion/1.0)',accept:'text/html,application/xhtml+xml'}});if(!r.ok||!(r.headers.get('content-type')||'').toLowerCase().includes('html'))return null;return{url:r.url||url,html:await r.text()};}catch{return null;}finally{clearTimeout(t);}}
function pageLinks(base:URL,html:string){const $=cheerio.load(html);const out:string[]=[];$('a[href]').each((_,el)=>{const href=$(el).attr('href')||'';const label=clean($(el).text());if(!/(superintendent|administration|leadership|district office|staff|directory)/i.test(`${label} ${href}`))return;try{const u=new URL(href,base);u.hash='';if(/^https?:$/.test(u.protocol)&&sameHost(base,u))out.push(u.toString());}catch{}});for(const p of PATHS)out.push(new URL(p,base).toString());return[...new Set(out)].slice(0,20);}
function extract(html:string,source:string){const $=cheerio.load(html);const hits:Hit[]=[];const selectors='article,li,tr,.staff,.staff-member,.staff-card,.person,.employee,.contact,.directory-item,.profile,.card,section';for(const node of $(selectors).toArray()){const n=$(node);const raw=n.text();const text=clean(raw);if(text.length<8||text.length>900||!TITLE_RX.test(text)||EXCLUDE_TITLE_RX.test(text))continue;const chunks=raw.split(/\r?\n|\||•/).map(clean).filter(Boolean);const title=chunks.find(x=>TITLE_RX.test(x)&&!EXCLUDE_TITLE_RX.test(x)&&x.length<=160)||'Superintendent';let full:string|null=null;for(const c of[n.find('.name,.staff-name,.person-name,.employee-name').first().text(),n.find('h1,h2,h3,h4,h5,strong,b').first().text(),...chunks.slice(0,6)]){full=plausibleName(c);if(full)break;}if(!full)continue;const mail=(n.find('a[href^="mailto:"]').first().attr('href')||'').replace(/^mailto:/i,'').split('?')[0];const tel=(n.find('a[href^="tel:"]').first().attr('href')||'').replace(/^tel:/i,'');const email=mail||text.match(EMAIL_RE)?.[0]||null;const phone=tel||text.match(PHONE_RE)?.[0]||null;hits.push({full_name:full,title,email,phone,source_url:source,score:(email?4:0)+(phone?2:0)+(title.length<100?1:0)});}const lines=$('body').text().split(/\r?\n/).map(clean).filter(x=>x.length>1&&x.length<180);for(let i=0;i<lines.length;i++){if(!TITLE_RX.test(lines[i])||EXCLUDE_TITLE_RX.test(lines[i]))continue;let full:string|null=null;for(const d of[-1,1,-2,2,-3,3]){const x=lines[i+d];if(x&&(full=plausibleName(x)))break;}if(!full)continue;const ctx=lines.slice(Math.max(0,i-4),Math.min(lines.length,i+5)).join(' ');hits.push({full_name:full,title:lines[i],email:ctx.match(EMAIL_RE)?.[0]||null,phone:ctx.match(PHONE_RE)?.[0]||null,source_url:source,score:(ctx.match(EMAIL_RE)?4:0)+(ctx.match(PHONE_RE)?2:0)+1});}return hits.sort((a,b)=>b.score-a.score)[0]||null;}
async function laneCount(sql:ReturnType<typeof getSql>,state:string){return (await sql.query(`select count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='verified')::int verified from raven_state_contacts where state_code=$1 and scope='district' and role_key='superintendent'`,[state]) as any[])[0];}
export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const started=Date.now();const unresolved=await sql.query(`select state_code,count(*) filter(where verification_status='missing')::int missing from raven_state_contacts where scope='district' and role_key='superintendent' and state_code=any($1::text[]) group by state_code having count(*) filter(where verification_status='missing')>0`,[STATES]) as any[];const byState=new Map(unresolved.map(r=>[r.state_code,Number(r.missing)]));const state=STATES.find(s=>(byState.get(s)||0)>0);if(!state)return NextResponse.json({ok:true,mode:'48-state-superintendents',complete:true,message:'All contiguous-state superintendent missing slots are zero.'});const before=await laneCount(sql,state);const agencies=await sql.query(`select a.id::text,a.canonical_name,a.website from agencies a join raven_state_contacts c on c.agency_id=a.id where c.state_code=$1 and c.scope='district' and c.role_key='superintendent' and c.verification_status='missing' and nullif(trim(a.website),'') is not null and a.website !~* '^https?://nces\\.ed\\.gov/' order by a.canonical_name limit $2`,[state,LIMIT]) as Agency[];let districts=0,pages=0,verified=0;const results:any[]=[];async function processAgency(a:Agency){if(Date.now()-started>BUDGET)return;const seed=safe(a.website);if(!seed)return;const home=await fetchHtml(seed.toString());if(!home)return;districts++;const base=safe(home.url)||seed;let best=extract(home.html,base.toString());pages++;for(const url of pageLinks(base,home.html)){if(Date.now()-started>BUDGET||best?.score>=7)break;const r=await fetchHtml(url);if(!r)continue;const u=safe(r.url);if(!u||!sameHost(base,u))continue;pages++;const h=extract(r.html,u.toString());if(h&&(!best||h.score>best.score))best=h;}if(!best)return;const rows=await sql.query(`update raven_state_contacts set full_name=$2,title=$3,email=$4,phone=$5,source_url=$6,verification_status='verified',verified_at=now(),evidence_note='Verified directly from current official district website by isolated 48-state superintendent worker; no contact field inferred.',updated_at=now() where agency_id=$1 and state_code=$7 and scope='district' and role_key='superintendent' and verification_status='missing' returning id::text`,[a.id,best.full_name,best.title,best.email,best.phone,best.source_url,state]) as any[];if(rows.length){verified+=rows.length;results.push({district:a.canonical_name,...best});}}
for(let i=0;i<agencies.length&&Date.now()-started<BUDGET;i+=CONCURRENCY)await Promise.all(agencies.slice(i,i+CONCURRENCY).map(processAgency));const after=await laneCount(sql,state);const remaining=await sql.query(`select state_code,count(*) filter(where verification_status='missing')::int missing from raven_state_contacts where scope='district' and role_key='superintendent' and state_code=any($1::text[]) group by state_code order by state_code`,[STATES]);const summary={ok:true,mode:'48-state-superintendents',state,districtsSelected:agencies.length,districtsProcessed:districts,pagesScanned:pages,verifiedAdded:verified,before,after,results,remaining,elapsedMs:Date.now()-started};console.log('RAVEN_SUPERINTENDENTS_48',summary);return NextResponse.json(summary);}
