export type K12PlatformStatus = "classified" | "connector_live" | "blocked" | "needs_review";

export interface K12PlatformRecord {
  stateCode: string;
  districtName: string;
  procurementPlatform: string;
  procurementUrl: string;
  scope: string;
  status: K12PlatformStatus;
  notes?: string;
}

export const K12_PLATFORM_REGISTRY: K12PlatformRecord[] = [
  {
    stateCode: "FL",
    districtName: "Miami-Dade County Public Schools",
    procurementPlatform: "DemandStar",
    procurementUrl: "https://procurement.dadeschools.net/appx/default.asp",
    scope: "non-construction solicitations",
    status: "classified",
    notes: "District procurement site states that M-DCPS partners with Onvia DemandStar for publishing and managing competitive non-construction solicitations; district site remains an additional publication surface.",
  },
  {
    stateCode: "FL",
    districtName: "Broward County Public Schools",
    procurementPlatform: "DemandStar",
    procurementUrl: "https://www.browardschools.com/bcps-departments/procurement/district-bid-opportunities-demandstar",
    scope: "current solicitations and addenda",
    status: "classified",
    notes: "District states all current solicitation/bid opportunities and addenda are posted through DemandStar Onvia, with electronic bid receipt through DemandStar.",
  },
  {
    stateCode: "FL",
    districtName: "Orange County Public Schools",
    procurementPlatform: "VendorLink",
    procurementUrl: "https://www.ocps.net/procurement-services-solicitations",
    scope: "goods and services solicitations and award notifications",
    status: "classified",
    notes: "OCPS states VendorLink is used for solicitation notifications, solicitation documents, and award notifications. Facilities and construction contracting has additional district pages and should be treated as a separate coverage lane.",
  },
  {
    stateCode: "TX",
    districtName: "Dallas Independent School District",
    procurementPlatform: "Bonfire",
    procurementUrl: "https://www.dallasisd.org/departments/procurement/vendor-opportunities",
    scope: "goods, services, and district procurement solicitations; construction/bond also references Bonfire with district publication pages",
    status: "classified",
    notes: "Dallas ISD states that bids are issued through Bonfire and its procurement site publishes current opportunity summaries. Construction and bond opportunities are also published on district pages and direct bidders to the same Bonfire portal.",
  },
  {
    stateCode: "TX",
    districtName: "Austin Independent School District",
    procurementPlatform: "Bonfire",
    procurementUrl: "https://www.austinisd.org/cp/bids",
    scope: "formal solicitations, notifications, electronic bid submission, and contract management",
    status: "classified",
    notes: "Austin ISD states it uses Bonfire for vendor registration, solicitation notification, electronic bid submission, and contract management, and links its Bonfire portal from the district bid-opportunities page.",
  },
  {
    stateCode: "TX",
    districtName: "Magnolia Independent School District",
    procurementPlatform: "Bonfire",
    procurementUrl: "https://www.magnoliaisd.org/departments/purchasing/bid-opportunities",
    scope: "open requests for proposals and online purchasing",
    status: "classified",
    notes: "Magnolia ISD states current open RFPs are posted on the district bid page and its Bonfire online purchasing system.",
  },
  {
    stateCode: "TX",
    districtName: "Comal Independent School District",
    procurementPlatform: "Bonfire",
    procurementUrl: "https://www.comalisd.org/apps/pages/current_bidding_opportunities",
    scope: "current bids and proposals with electronic response submission",
    status: "classified",
    notes: "Comal ISD states it partnered with Bonfire Interactive for procurement opportunity notifications and digital bid/proposal responses and links comalisd.bonfirehub.com as its portal.",
  },
  {
    stateCode: "TX",
    districtName: "Amarillo Independent School District",
    procurementPlatform: "Bonfire",
    procurementUrl: "https://amaisd.org/146923_3",
    scope: "current bid opportunities and vendor notifications",
    status: "classified",
    notes: "Amarillo ISD Purchasing states it uses Bonfire as its web-based eProcurement service for current bid opportunities and vendor notifications.",
  },
  {
    stateCode: "TX",
    districtName: "Laredo Independent School District",
    procurementPlatform: "Bonfire",
    procurementUrl: "https://www.laredoisd.org/page/procurement",
    scope: "district solicitations and bid notifications",
    status: "classified",
    notes: "Laredo ISD states it is soliciting bids through the Bonfire e-bid system and directs vendors to the LISD Bonfire portal for upcoming opportunities.",
  },
  {
    stateCode: "TX",
    districtName: "Temple Independent School District",
    procurementPlatform: "Euna Procurement / Bonfire",
    procurementUrl: "https://www.tisd.org/apps/pages/index.jsp?pREC_ID=1668869&type=d&uREC_ID=339301",
    scope: "bid opportunities and electronic procurement",
    status: "classified",
    notes: "Temple ISD identifies Euna, formerly Bonfire, as its strategic sourcing and procurement platform and directs vendors to its e-bidding portal for opportunities.",
  },
  {
    stateCode: "TX",
    districtName: "Houston Independent School District",
    procurementPlatform: "Euna Procurement / IonWave",
    procurementUrl: "https://www.houstonisd.org/community-partnerships/purchasing-services",
    scope: "current bids, solicitation documents, addenda, and electronic proposal submission",
    status: "connector_live",
    notes: "Houston ISD states it has transitioned to fully electronic bidding through IonWave and that procurement documents are available exclusively through the electronic bidding portal. Pursuit's IonWave opportunity connector is live; document acquisition remains a separate verification gate.",
  },
  {
    stateCode: "TX",
    districtName: "Northside Independent School District",
    procurementPlatform: "Euna Procurement / Bonfire",
    procurementUrl: "https://www.nisd.net/district/purchasing/business-with-nisd",
    scope: "bid opportunity notifications, documents, and electronic submissions",
    status: "classified",
    notes: "Northside ISD states its Purchasing Office uses Bonfire Interactive for vendor registration, opportunity notifications, and electronic bid submission.",
  },
  {
    stateCode: "TX",
    districtName: "Katy Independent School District",
    procurementPlatform: "OpenGov",
    procurementUrl: "https://www.katyisd.org/purchasing/bid-proposal-opportunities",
    scope: "solicitation notifications, submissions, amendments, awards, and contract management",
    status: "classified",
    notes: "Katy ISD's current bid-opportunities page states it implemented OpenGov as its new eProcurement solution. Older district pages still mention Bonfire; the current procurement page is treated as authoritative for present classification.",
  },
  {
    stateCode: "TX",
    districtName: "Fort Worth Independent School District",
    procurementPlatform: "Euna Procurement / IonWave",
    procurementUrl: "https://www.fwisd.org/departments/procurement-services",
    scope: "all district solicitations, notifications, solicitation information, and electronic responses",
    status: "classified",
    notes: "Fort Worth ISD states all solicitations and procurement opportunities are advertised on IonWave and identifies IonWave as the district eBid portal.",
  },
  {
    stateCode: "CA",
    districtName: "Los Angeles Unified School District",
    procurementPlatform: "SAP Ariba + district solicitation site",
    procurementUrl: "https://procurement.lausd.org/apps/pages/Solicitations",
    scope: "purchasing and contracting opportunities across professional services, goods/general services, A&E, and public works",
    status: "classified",
    notes: "LAUSD states that procurement activities have migrated to SAP Ariba while its Procurement Services Division maintains a consolidated solicitation website for purchasing and contracting opportunities. Treat Ariba and the district solicitation site as complementary sources until a production connector is verified.",
  },
  {
    stateCode: "NV",
    districtName: "Clark County School District",
    procurementPlatform: "Bonfire + DemandStar",
    procurementUrl: "https://www.ccsd.net/resources/purchasing-and-warehousing",
    scope: "competitive goods, commodities, and non-construction service solicitations",
    status: "classified",
    notes: "CCSD states competitive opportunity downloads and submissions are available through its Bonfire portal, while DemandStar maintains the bidders list and automatic bid notifications. Bonfire is the primary connector target; DemandStar is a complementary notification source.",
  },
  {
    stateCode: "IL",
    districtName: "Chicago Public Schools",
    procurementPlatform: "CPS Contracting Opportunities + CPS Supplier Portal",
    procurementUrl: "https://www.cps.edu/procurement/contracting-opportunities/",
    scope: "public bids, RFPs, RFQs, prequalified construction opportunities, sourcing plan, and vendor responses",
    status: "classified",
    notes: "CPS publishes current contracting opportunities on its own procurement inventory. The CPS Supplier Portal supports active supplier purchase orders, invoice/payment status, and supplier administration; it is not treated as the public solicitation source.",
  },
];
