import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const SOURCE = "https://adedata.arkansas.gov/statewide/reportlist/districts/SuperintendentContactList.aspx";
const PAGE_COUNT = 26;

type Contact = { district:string; lea:string; fullName:string; email:string|null; phone:string|null };
type Slot = { id:string; agency_id:string; canonical_name:string; verification_status:string };

function decode(s:string){return s.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/<br\s*\/?\s*>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function cells(row:string){return Array.from(row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)).map(m=>decode(m[1]));}
function person(v:string){const x=decode(v).replace(/\s+/g," ").trim();if(!x)return "";if(x.includes(",")){const [last,...rest]=x.split(",");return `${rest.join(",").trim()} ${last.trim()}`.replace(/\s+/g," ").trim();}return x;}
function parse(html:string):Contact[]{const out:Contact[]=[];for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const c=cells(m[1]);if(c.length<9)continue;const lea=(c[0]||"").replace(/\D/g,"");const district=(c[1]||"").trim();const fullName=person(c[2]||"");const phone=(c[7]||"").trim()||null;const email=(c[8]||"").trim();if(!/^\d{7}$/.test(lea)||!district||!fullName)continue;out.push({district,lea,fullName,email:/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(email)?email:null,phone});}return out;}
async function fetchRoster(){const pages=await Promise.all(Array.from({length:PAGE_COUNT},async(_,i)=>{const page=i+1;const url=`${SOURCE}?page=${page}`;const res=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 Raven/1.0","accept":"text/html,application/xhtml+xml"},cache:"no-store"});const html=await res.text();const contacts=res.ok?parse(html):[];return {page,status:res.status,htmlBytes:html.length,contacts};}));const bad=pages.filter(p=>p.status!==200||p.contacts.length===0);if(bad.length)throw new Error(`Arkansas ADE page failure ${JSON.stringify(bad.map(x=>({page:x.page,status:x.status,parsed:x.contacts.length})))}`);const map=new Map<string,Contact>();for(const p of pages)for(const c of p.contacts)map.set(c.lea,c);return {contacts:[...map.values()],pages};}
function norm(v:string){return (v||"").toLowerCase().replace(/\bpublic charter schools\b/g," ").replace(/\bpublic schools\b/g," ").replace(/\bschool district\b/g," ").replace(/\bschools\b/g," ").replace(/\bschool\b/g," ").replace(/\bdistrict\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function match(c:Contact, slots:Slot[]){const n=norm(c.district);const exact=slots.filter(s=>norm(s.canonical_name)===n);if(exact.length===1)return exact[0];const compact=n.replace(/\s+/g,"");const near=slots.filter(s=>{const x=norm(s.canonical_name).replace(/\s+/g,"");return x===compact||(x.length>5&&compact.length>5&&(x.includes(compact)||compact.includes(x)));});return near.length===1?near[0]:null;}
async function counts(sql:ReturnType<typeof getSql>){return (await sql.query(`select count(*)::int total,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts`) as any[])[0];}

export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=await counts(sql);const beforeState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing from raven_state_contacts where state_code='AR' and role_key='superintendent'`) as any[])[0].missing;
 let roster:{contacts:Contact[];pages:{page:number;status:number;htmlBytes:number;contacts:Contact[]}[]};try{roster=await fetchRoster();}catch(e){console.log("RAVEN_AR_BULK_DIAG",{error:String(e),beforeState});return NextResponse.json({ok:false,state:"AR",error:String(e),before,beforeStateMissing:beforeState},{status:502});}
 console.log("RAVEN_AR_BULK_DIAG",{pages:roster.pages.length,parsed:roster.contacts.length,pageCounts:roster.pages.map(p=>p.contacts.length),beforeState});if(roster.contacts.length<220)return NextResponse.json({ok:false,state:"AR",error:"Statewide roster guard: too few superintendent records",parsed:roster.contacts.length,before,beforeStateMissing:beforeState},{status:502});
 const slots=await sql.query(`select c.id::text,c.agency_id::text,a.canonical_name,c.verification_status from raven_state_contacts c join agencies a on a.id=c.agency_id where c.state_code='AR' and c.scope='district' and c.role_key='superintendent'`) as Slot[];let matched=0,filled=0,peopleWritten=0;const touched=new Set<string>();const unmatched:string[]=[];
 for(const c of roster.contacts){const s=match(c,slots);if(!s){unmatched.push(c.district);continue;}matched++;touched.add(s.agency_id);await sql.query(`insert into raven_people(agency_id,full_name,title,role_family,email,phone,source_url,source_type,confidence,last_verified_at,updated_at) values($1,$2,'Superintendent','Executive',$3,$4,$5,'state_education_directory',98,now(),now()) on conflict(agency_id,full_name,title) do update set email=excluded.email,phone=excluded.phone,source_url=excluded.source_url,source_type=excluded.source_type,confidence=greatest(raven_people.confidence,excluded.confidence),last_verified_at=now(),updated_at=now()`,[s.agency_id,c.fullName,c.email,c.phone,SOURCE]);peopleWritten++;const r=await sql.query(`update raven_state_contacts set full_name=$2,title='Superintendent',email=$3,phone=$4,source_url=$5,verification_status='candidate',evidence_note='Current superintendent, phone and direct email published in the Arkansas Department of Education statewide Superintendent Contact List by District; fields copied exactly as published.',updated_at=now() where id=$1 and verification_status in ('missing','rejected') returning id`,[s.id,c.fullName,c.email,c.phone,SOURCE]) as any[];filled+=r.length;}
 const after=await counts(sql);const afterState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='AR' and role_key='superintendent'`) as any[])[0];const summary={ok:true,state:'AR',role:'superintendent',source:SOURCE,pages:roster.pages.length,parsedSuperintendents:roster.contacts.length,districtsProcessedInBulk:touched.size,matched,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,20),peopleWritten,filled,beforeStateMissing:beforeState,afterState,before,after,net:{total:after.total-before.total,verified:after.verified-before.verified,candidate:after.candidate-before.candidate,missing:after.missing-before.missing,rejected:after.rejected-before.rejected}};console.log("RAVEN_AR_BULK",summary);return NextResponse.json(summary);}
