import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const SOURCE = "https://mdek12.org/dd/";

type Contact={district:string;fullName:string;title:string;email:string|null;phone:string|null};
type Slot={id:string;agency_id:string;canonical_name:string;verification_status:string};

function decode(s:string){return s.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/&ndash;|&mdash;/gi,"-").replace(/&#8211;|&#8212;/g,"-");}
function lines(html:string){const text=decode(html).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/(p|div|li|h[1-6]|tr|td|section|article)>/gi,"\n").replace(/<[^>]+>/g," ");return text.split(/\n+/).map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean);}
function districtish(v:string){return /\b(school district|public school district|public schools|municipal school district|separate school district|consolidated school district)\b/i.test(v) && !/district directory|superintendent changes|school districts? appoint/i.test(v);}
function parseRoster(html:string):Contact[]{const a=lines(html);const out:Contact[]=[];const email=/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;const phone=/\(?\d{3}\)?[ .-]\d{3}[ .-]\d{4}/;for(let i=0;i<a.length;i++){if(!districtish(a[i]))continue;let titleIdx=-1;for(let j=i+1;j<=Math.min(a.length-1,i+5);j++){if(/\bsuperintendent\b/i.test(a[j])){titleIdx=j;break;}if(districtish(a[j]))break;}if(titleIdx<0)continue;const personLine=a[titleIdx];const comma=personLine.lastIndexOf(",");if(comma<1)continue;const fullName=personLine.slice(0,comma).replace(/^(Dr\.|Mr\.|Mrs\.|Ms\.)\s+/i,"").trim();const title=personLine.slice(comma+1).trim();if(!fullName||!/superintendent/i.test(title))continue;let e:string|null=null,p:string|null=null;for(let j=titleIdx+1;j<=Math.min(a.length-1,titleIdx+12);j++){if(j>titleIdx+1&&districtish(a[j]))break;if(!e&&email.test(a[j]))e=a[j];if(!p){const m=a[j].match(phone);if(m&&!/^FAX/i.test(a[j]))p=m[0];}}out.push({district:a[i].replace(/\s*\([^)]*County[^)]*\)\s*$/i,"").trim(),fullName,title,email:e,phone:p});}const dedup=new Map<string,Contact>();for(const c of out)dedup.set(norm(c.district),c);return [...dedup.values()];}
function norm(v:string){return (v||"").toLowerCase().replace(/[“”'’]/g,"").replace(/&/g," and ").replace(/\bcounty school district\b/g," county ").replace(/\bpublic school district\b/g," ").replace(/\bmunicipal school district\b/g," ").replace(/\bseparate school district\b/g," ").replace(/\bconsolidated school district\b/g," ").replace(/\bschool district\b/g," ").replace(/\bpublic schools\b/g," ").replace(/\bschools\b/g," ").replace(/\bschool\b/g," ").replace(/\bdist\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function match(c:Contact,slots:Slot[]){const n=norm(c.district);const exact=slots.filter(s=>norm(s.canonical_name)===n);if(exact.length===1)return exact[0];const compact=n.replace(/\s+/g,"");const near=slots.filter(s=>{const x=norm(s.canonical_name).replace(/\s+/g,"");return x===compact||(x.length>6&&compact.length>6&&(x.includes(compact)||compact.includes(x)));});return near.length===1?near[0]:null;}
async function counts(sql:ReturnType<typeof getSql>){return (await sql.query(`select count(*)::int total,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts`) as any[])[0];}

export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=await counts(sql);const beforeState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing from raven_state_contacts where state_code='MS' and role_key='superintendent'`) as any[])[0].missing;
 let res:Response;try{res=await fetch(SOURCE,{headers:{"user-agent":"Mozilla/5.0 Raven/1.0","accept":"text/html,application/xhtml+xml"},redirect:"follow",cache:"no-store"});}catch(e){return NextResponse.json({ok:false,state:"MS",error:`MDE fetch ${String(e)}`,beforeStateMissing:beforeState},{status:502});}if(!res.ok)return NextResponse.json({ok:false,state:"MS",error:`MDE ${res.status}`,beforeStateMissing:beforeState},{status:502});
 const roster=parseRoster(await res.text());if(roster.length<120)return NextResponse.json({ok:false,state:"MS",source:SOURCE,error:"Statewide roster guard: too few superintendent records",parsed:roster.length,beforeStateMissing:beforeState},{status:502});
 const slots=await sql.query(`select c.id::text,c.agency_id::text,a.canonical_name,c.verification_status from raven_state_contacts c join agencies a on a.id=c.agency_id where c.state_code='MS' and c.scope='district' and c.role_key='superintendent'`) as Slot[];
 let matched=0,filled=0,peopleWritten=0;const touched=new Set<string>();const unmatched:string[]=[];
 for(const c of roster){const s=match(c,slots);if(!s){unmatched.push(c.district);continue;}matched++;touched.add(s.agency_id);await sql.query(`insert into raven_people(agency_id,full_name,title,role_family,email,phone,source_url,source_type,confidence,last_verified_at,updated_at) values($1,$2,$3,'Executive',$4,$5,$6,'state_education_directory',95,now(),now()) on conflict(agency_id,full_name,title) do update set email=excluded.email,phone=excluded.phone,source_url=excluded.source_url,source_type=excluded.source_type,confidence=greatest(raven_people.confidence,excluded.confidence),last_verified_at=now(),updated_at=now()`,[s.agency_id,c.fullName,c.title,c.email,c.phone,SOURCE]);peopleWritten++;
 const r=await sql.query(`update raven_state_contacts set full_name=$2,title=$3,email=$4,phone=$5,source_url=$6,verification_status='candidate',evidence_note='Current superintendent published in the Mississippi Department of Education statewide District Directory; direct contact fields copied exactly when published.',updated_at=now() where id=$1 and verification_status in ('missing','rejected') returning id`,[s.id,c.fullName,c.title,c.email,c.phone,SOURCE]) as any[];filled+=r.length;}
 const after=await counts(sql);const afterState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='MS' and role_key='superintendent'`) as any[])[0];
 return NextResponse.json({ok:true,state:"MS",role:"superintendent",source:SOURCE,parsedSuperintendents:roster.length,districtsProcessedInBulk:touched.size,matched,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,20),peopleWritten,filled,beforeStateMissing:beforeState,afterState,before,after,net:{total:after.total-before.total,verified:after.verified-before.verified,candidate:after.candidate-before.candidate,missing:after.missing-before.missing,rejected:after.rejected-before.rejected}});}
