import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const SOURCE = "https://apps.opi.mt.gov/OPIReportingCenter/frmCentralDirectory.aspx?ProcName=procCentralDirectorySystemStaffBySystem&Role=SUPT&ScreenMsg=+Database+of+Montana+District+Superintendents&ScreenTitle=District+Superintendents&SelectRole=1&ShowReport=1";

type Contact={system:string;fullName:string;title:string;email:string|null;phone:string|null};
type Slot={id:string;agency_id:string;canonical_name:string;verification_status:string};

function decode(s:string){return s.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/&ndash;|&mdash;/gi,"-").replace(/<br\s*\/?\s*>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function cells(row:string){return Array.from(row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)).map(m=>decode(m[1]));}
function parseContacts(html:string):Contact[]{const out:Contact[]=[];for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const c=cells(m[1]);if(c.length<15)continue;const system=c[2]?.trim();const email=c[8]?.trim()||null;const phone=c[9]?.trim()||null;const first=c[12]?.trim();const last=c[13]?.trim();const title=c[14]?.trim();if(!system||!first||!last||!title||!/superintendent/i.test(title))continue;out.push({system,fullName:`${first} ${last}`.replace(/\s+/g," ").trim(),title,email:email&&/@/.test(email)?email:null,phone:phone||null});}return out;}
function hidden(html:string){const p=new URLSearchParams();for(const m of html.matchAll(/<input\b[^>]*type=["']hidden["'][^>]*>/gi)){const tag=m[0];const nm=tag.match(/\bname=["']([^"']+)["']/i)?.[1];const val=tag.match(/\bvalue=["']([^"']*)["']/i)?.[1]||"";if(nm)p.set(nm,decode(val));}return p;}
function pager(html:string){const hits=Array.from(html.matchAll(/__doPostBack\('([^']+)','Page\$(\d+)'\)/g));if(!hits.length)return null;const target=hits[0][1];const max=Math.max(...hits.map(h=>Number(h[2])).filter(Number.isFinite));return {target,max};}
async function fetchRoster(){let res=await fetch(SOURCE,{headers:{"user-agent":"Mozilla/5.0 Raven/1.0"},cache:"no-store"});if(!res.ok)throw new Error(`Montana OPI GET ${res.status}`);let html=await res.text();let all=parseContacts(html);const pg=pager(html);let pages=1;if(pg){const max=Math.min(pg.max,50);for(let page=2;page<=max;page++){const form=hidden(html);form.set("__EVENTTARGET",pg.target);form.set("__EVENTARGUMENT",`Page$${page}`);res=await fetch(SOURCE,{method:"POST",headers:{"user-agent":"Mozilla/5.0 Raven/1.0","content-type":"application/x-www-form-urlencoded"},body:form.toString(),cache:"no-store"});if(!res.ok)throw new Error(`Montana OPI page ${page} ${res.status}`);html=await res.text();const batch=parseContacts(html);if(!batch.length)throw new Error(`Montana OPI page ${page} parsed 0 contacts`);all.push(...batch);pages++;}}
 const dedup=new Map<string,Contact>();for(const c of all)dedup.set(`${c.system.toLowerCase()}|${c.fullName.toLowerCase()}`,c);return {contacts:[...dedup.values()],pages};}
function norm(v:string){return (v||"").toLowerCase().replace(/\bco\b/g,"county").replace(/\bschls\b/g,"schools").replace(/\bk\s*-\s*12\b/g,"k12").replace(/\bpublic\b/g," ").replace(/\bschool system\b/g," ").replace(/\bschool district\b/g," ").replace(/\bdistrict\b/g," ").replace(/\bschools\b/g," ").replace(/\bschool\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function match(contact:Contact,slots:Slot[]){const n=norm(contact.system);const exact=slots.filter(s=>norm(s.canonical_name)===n);if(exact.length===1)return exact[0];const compact=n.replace(/\s+/g,"");const near=slots.filter(s=>{const x=norm(s.canonical_name).replace(/\s+/g,"");return x===compact||(x.length>5&&compact.length>5&&(x.includes(compact)||compact.includes(x)));});return near.length===1?near[0]:null;}
async function counts(sql:ReturnType<typeof getSql>){return (await sql.query(`select count(*)::int total,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts`) as any[])[0];}

export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=await counts(sql);const beforeState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing from raven_state_contacts where state_code='MT' and role_key='superintendent'`) as any[])[0].missing;
 let roster:{contacts:Contact[];pages:number};try{roster=await fetchRoster();}catch(e){return NextResponse.json({ok:false,state:"MT",source:SOURCE,error:String(e),before,beforeStateMissing:beforeState},{status:502});}
 if(roster.contacts.length<150)return NextResponse.json({ok:false,state:"MT",source:SOURCE,error:"Statewide roster guard: too few superintendent records",parsed:roster.contacts.length,pages:roster.pages,before,beforeStateMissing:beforeState},{status:502});
 const slots=await sql.query(`select c.id::text,c.agency_id::text,a.canonical_name,c.verification_status from raven_state_contacts c join agencies a on a.id=c.agency_id where c.state_code='MT' and c.scope='district' and c.role_key='superintendent'`) as Slot[];
 let matched=0,filled=0,peopleWritten=0;const touched=new Set<string>();const unmatched:string[]=[];
 for(const c of roster.contacts){const s=match(c,slots);if(!s){unmatched.push(c.system);continue;}matched++;touched.add(s.agency_id);await sql.query(`insert into raven_people(agency_id,full_name,title,role_family,email,phone,source_url,source_type,confidence,last_verified_at,updated_at) values($1,$2,$3,'Executive',$4,$5,$6,'state_education_directory',95,now(),now()) on conflict(agency_id,full_name,title) do update set email=excluded.email,phone=excluded.phone,source_url=excluded.source_url,source_type=excluded.source_type,confidence=greatest(raven_people.confidence,excluded.confidence),last_verified_at=now(),updated_at=now()`,[s.agency_id,c.fullName,c.title,c.email,c.phone,SOURCE]);peopleWritten++;
 const r=await sql.query(`update raven_state_contacts set full_name=$2,title=$3,email=$4,phone=$5,source_url=$6,verification_status='candidate',evidence_note='Current district superintendent published in the Montana Office of Public Instruction statewide District Superintendents report; direct contact fields copied exactly when published.',updated_at=now() where id=$1 and verification_status in ('missing','rejected') returning id`,[s.id,c.fullName,c.title,c.email,c.phone,SOURCE]) as any[];filled+=r.length;}
 const after=await counts(sql);const afterState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='MT' and role_key='superintendent'`) as any[])[0];
 return NextResponse.json({ok:true,state:"MT",role:"superintendent",source:SOURCE,pages:roster.pages,parsedSuperintendents:roster.contacts.length,districtsProcessedInBulk:touched.size,matched,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,20),peopleWritten,filled,beforeStateMissing:beforeState,afterState,before,after,net:{total:after.total-before.total,verified:after.verified-before.verified,candidate:after.candidate-before.candidate,missing:after.missing-before.missing,rejected:after.rejected-before.rejected}});}
