import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const SOURCE = "https://educdirsrc.education.ne.gov/QuickDisplay.aspx?code=alld&sort=agencyid";

type Contact={agencyCode:string;district:string;fullName:string;email:string|null;phone:string|null};
type Slot={id:string;agency_id:string;canonical_name:string;verification_status:string};

function decode(s:string){return s.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/<br\s*\/?\s*>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function cells(row:string){return Array.from(row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)).map(m=>decode(m[1]));}
function parse(html:string){const rows:Array<{cells:string[]}> = [];for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const c=cells(m[1]);if(c.length>=10)rows.push({cells:c});}
 const contacts:Contact[]=[];for(const r of rows){const c=r.cells;let idx=c.findIndex(x=>/^\d{2}-\d{4}-\d{3}$/.test(x));if(idx<0)continue;const agencyCode=c[idx];const fullName=(c[idx-1]||"").trim();const district=(c[idx+1]||"").trim();if(!district)continue;const email=c.find(x=>/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(x))||null;const phone=c.find(x=>/^\(?\d{3}\)?[- .]\d{3}[- .]\d{4}$/.test(x))||null;if(fullName&&email)contacts.push({agencyCode,district,fullName,email,phone});}
 const dedup=new Map<string,Contact>();for(const c of contacts)dedup.set(c.agencyCode,c);return {rows:rows.length,contacts:[...dedup.values()]};}
function norm(v:string){return (v||"").toLowerCase().replace(/\bcommunity schools\b/g," ").replace(/\bpublic schools\b/g," ").replace(/\bpublic school\b/g," ").replace(/\bschool district\b/g," ").replace(/\bcommunity school\b/g," ").replace(/\bconsolidated schools\b/g," ").replace(/\bschools\b/g," ").replace(/\bschool\b/g," ").replace(/\bdistrict\b/g," ").replace(/\bsch\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function match(c:Contact,slots:Slot[]){const n=norm(c.district);const exact=slots.filter(s=>norm(s.canonical_name)===n);if(exact.length===1)return exact[0];const compact=n.replace(/\s+/g,"");const near=slots.filter(s=>{const x=norm(s.canonical_name).replace(/\s+/g,"");return x===compact||(x.length>6&&compact.length>6&&(x.includes(compact)||compact.includes(x)));});return near.length===1?near[0]:null;}
async function counts(sql:ReturnType<typeof getSql>){return (await sql.query(`select count(*)::int total,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts`) as any[])[0];}

export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=await counts(sql);const beforeState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing from raven_state_contacts where state_code='NE' and role_key='superintendent'`) as any[])[0].missing;
 const res=await fetch(SOURCE,{headers:{"user-agent":"Mozilla/5.0 Raven/1.0","accept":"text/html,application/xhtml+xml"},cache:"no-store"});const html=await res.text();if(!res.ok)return NextResponse.json({ok:false,state:'NE',error:`NDE ${res.status}`,before,beforeStateMissing:beforeState},{status:502});const parsed=parse(html);console.log('RAVEN_NE_BULK_DIAG',{rows:parsed.rows,contacts:parsed.contacts.length,beforeState});if(parsed.rows<400||parsed.contacts.length<180)return NextResponse.json({ok:false,state:'NE',error:'Statewide roster guard: Nebraska NDE directory parsed too few records',rows:parsed.rows,contacts:parsed.contacts.length,before,beforeStateMissing:beforeState},{status:502});
 const slots=await sql.query(`select c.id::text,c.agency_id::text,a.canonical_name,c.verification_status from raven_state_contacts c join agencies a on a.id=c.agency_id where c.state_code='NE' and c.scope='district' and c.role_key='superintendent'`) as Slot[];let matched=0,filled=0,peopleWritten=0;const touched=new Set<string>();const unmatched:string[]=[];
 for(const c of parsed.contacts){const s=match(c,slots);if(!s){unmatched.push(c.district);continue;}matched++;touched.add(s.agency_id);await sql.query(`insert into raven_people(agency_id,full_name,title,role_family,email,phone,source_url,source_type,confidence,last_verified_at,updated_at) values($1,$2,'Superintendent','Executive',$3,$4,$5,'state_education_directory',98,now(),now()) on conflict(agency_id,full_name,title) do update set email=excluded.email,phone=excluded.phone,source_url=excluded.source_url,source_type=excluded.source_type,confidence=greatest(raven_people.confidence,excluded.confidence),last_verified_at=now(),updated_at=now()`,[s.agency_id,c.fullName,c.email,c.phone,SOURCE]);peopleWritten++;const r=await sql.query(`update raven_state_contacts set full_name=$2,title='Superintendent',email=$3,phone=$4,source_url=$5,verification_status='candidate',evidence_note='Current administrator and direct email published by the Nebraska Department of Education statewide Directory Search; fields copied exactly as published.',updated_at=now() where id=$1 and verification_status in ('missing','rejected') returning id`,[s.id,c.fullName,c.email,c.phone,SOURCE]) as any[];filled+=r.length;}
 const after=await counts(sql);const afterState=(await sql.query(`select count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='NE' and role_key='superintendent'`) as any[])[0];const summary={ok:true,state:'NE',role:'superintendent',source:SOURCE,parsedDirectoryRows:parsed.rows,parsedAdministratorsWithEmail:parsed.contacts.length,districtsProcessedInBulk:touched.size,matched,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,20),peopleWritten,filled,beforeStateMissing:beforeState,afterState,before,after,net:{total:after.total-before.total,verified:after.verified-before.verified,candidate:after.candidate-before.candidate,missing:after.missing-before.missing,rejected:after.rejected-before.rejected}};console.log('RAVEN_NE_BULK',summary);return NextResponse.json(summary);}
