import * as cheerio from "cheerio";
import { NextRequest, NextResponse } from "next/server";
import { getSql } from "@/lib/db";
import { requireInternalAuth } from "@/lib/internal-auth";

export const dynamic="force-dynamic";
export const maxDuration=300;
const SOURCE="https://pub.education.mn.gov/MdeOrgView/search/tagged/MDEORG_UUL_LEA";
const BASE="https://pub.education.mn.gov";

type Contact={code:string;district:string;fullName:string;email:string|null;phone:string|null;sourceUrl:string};
type Org={code:string;district:string;email:string|null;phone:string|null;href:string};
type Slot={id:string;canonical_name:string|null;county:string|null};
function clean(v:any){return String(v??"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim();}
function norm(v:any){return clean(v).toLowerCase().replace(/&/g," and ").replace(/\b(public|school|schools|district|independent|common|special|community)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function email(v:string){return (clean(v).match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||null;}
function phone(v:string){return (clean(v).match(/\(?\d{3}\)?[- .]\d{3}[- .]\d{4}/)||[])[0]||null;}
function abs(h:string){try{return new URL(h,BASE).toString();}catch{return h;}}
async function mapLimit<T,R>(xs:T[],n:number,fn:(x:T)=>Promise<R>):Promise<R[]>{const out=new Array<R>(xs.length);let i=0;async function w(){while(true){const j=i++;if(j>=xs.length)return;out[j]=await fn(xs[j]);}}await Promise.all(Array.from({length:Math.min(n,xs.length)},()=>w()));return out;}
async function roster(){
 const r=await fetch(SOURCE,{cache:"no-store",redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; Pursuit-Raven/14.0; authoritative-state-database)",accept:"text/html,application/xhtml+xml"}});
 if(!r.ok)throw new Error(`MDE-ORG tagged collection HTTP ${r.status}`);
 const $=cheerio.load(await r.text());const orgs:Org[]=[];
 $("table tr").each((_,tr)=>{const td=$(tr).find("td");if(td.length<4)return;const code=clean($(td[0]).text());const m=code.match(/^(\d{4})-(01|02|03)$/);if(!m)return;const district=clean($(td[1]).text());const href=$(td[0]).find("a").attr("href")||$(td[1]).find("a").attr("href")||"";if(!district||!href)return;orgs.push({code,district,email:email($(td[2]).text()),phone:phone($(td[3]).text()),href:abs(href)});});
 const unique=[...new Map(orgs.map(o=>[o.code,o])).values()];if(unique.length<300)throw new Error(`MDE-ORG statewide guard: only ${unique.length} regular district organizations found`);
 const rows=await mapLimit(unique,18,async o=>{try{const rr=await fetch(o.href,{cache:"no-store",redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; Pursuit-Raven/14.0; authoritative-state-database)",accept:"text/html"}});if(!rr.ok)return null;const $$=cheerio.load(await rr.text());let fullName="";$$('a').each((_,a)=>{if(fullName)return;const t=clean($$(a).text());const m=t.match(/^Superintendent\s+(.+)$/i);if(m)fullName=clean(m[1]).replace(/^(Dr\.?|Mr\.?|Mrs\.?|Ms\.?)\s+/i,"");});if(!fullName){const all=clean($$('body').text());const m=all.match(/Superintendent\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,4})/);if(m)fullName=clean(m[1]);}if(!fullName||fullName.split(/\s+/).length<2)return null;return {code:o.code,district:o.district,fullName,email:o.email,phone:o.phone,sourceUrl:o.href} as Contact;}catch{return null;}});
 const contacts=rows.filter((x):x is Contact=>!!x);if(contacts.length<280)throw new Error(`MDE-ORG superintendent guard: only ${contacts.length} current superintendent contacts parsed; no writes performed`);return contacts;
}
function match(c:Contact,slots:Slot[]){const k=norm(c.district);let a=slots.filter(s=>norm(s.canonical_name)===k);if(a.length===1)return a[0];a=slots.filter(s=>{const x=norm(s.canonical_name);return x&&k&&(x.includes(k)||k.includes(x));});return a.length===1?a[0]:null;}
export async function GET(req:NextRequest){const auth=requireInternalAuth(req);if(auth)return auth;const sql=getSql();const before=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='MN' and scope='district' and role_key='superintendent'`)as any[])[0];let list:Contact[]=[];try{list=await roster();}catch(e){return NextResponse.json({ok:false,state:'MN',source:SOURCE,blocker:e instanceof Error?e.message:String(e),before},{status:502});}const slots=await sql.query(`select c.id::text,c.county,a.canonical_name from raven_state_contacts c left join agencies a on a.id=c.agency_id where c.state_code='MN' and c.scope='district' and c.role_key='superintendent'`)as Slot[];let matched=0,written=0;const unmatched:string[]=[];for(const c of list){const s=match(c,slots);if(!s){unmatched.push(`${c.code} ${c.district}`);continue;}matched++;const u=await sql.query(`update raven_state_contacts set full_name=$2,title='Superintendent',email=$3,phone=$4,source_url=$5,verification_status='verified',verified_at=now(),evidence_note='Current superintendent contact published in Minnesota Department of Education MDE-ORG; district organization type is Independent, Common, or Special District.',updated_at=now() where id=$1 and verification_status in ('missing','candidate','rejected') returning id`,[s.id,c.fullName,c.email,c.phone,c.sourceUrl])as any[];written+=u.length;}const after=(await sql.query(`select count(*)::int slots,count(*) filter(where verification_status='verified')::int verified,count(*) filter(where verification_status='candidate')::int candidate,count(*) filter(where verification_status='missing')::int missing,count(*) filter(where verification_status='rejected')::int rejected from raven_state_contacts where state_code='MN' and scope='district' and role_key='superintendent'`)as any[])[0];return NextResponse.json({ok:true,state:'MN',source:SOURCE,parsed:list.length,matched,written,unmatchedSourceRecords:unmatched.length,unmatchedSample:unmatched.slice(0,25),before,after,verifiedAdded:Number(after.verified)-Number(before.verified)});}
